### ISSUE TITLE
Wrong PHP install using install.sh

### ISSUE THREAD

**Issue by Conver** [arevindh/pihole-speedtest#3] opened 2018-09-13 00:04 UTC
Hello,

I believe there is an typo in your install.sh

https://github.com/arevindh/pihole-speedtest/blob/master/install.sh#L15

If PHP 5 is found it install for PHP 7 and same the other way around.

It seems to only be a typo as the right version is install when uncomment.

**Comment by arevindh** [comment] 2018-09-13 03:13
Hi @Conver, fixed the typo. Please close the issue if the issue is fixed

**Closed** 2018-09-13 03:14 UTC
