### ISSUE TITLE
Scheduled Tests Fail to Run & Invalid Date error in Speedtest Log table

### ISSUE THREAD

**Issue by town3r** [arevindh/pihole-speedtest#154] opened 2024-01-23 14:36 UTC
Hi there!

I'm back, reinstalled the plugin yesterday after the install/update script was updated.

It seemed to be working correctly, but I failed to notice the scheduled tests were not either running successfully, or failing to be detected by the plugin.

I did notice that the Run Test Now option does not seem to work w/ my installation.

The Speedtest Log table is also showing Invalid date under the Test time column.

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/f7bbbd8e-820c-4872-bf22-adc9f787d485)

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/ef52c753-c9cb-479f-82d5-ff832fb84c79)

Any idea what could be occurring?

The few tests that do show up were ran via the Test Pihole Speedtest from command line command:

`sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest.sh"`

**Comment by arevindh** [comment] 2024-01-23 16:08
@town3r 

1. which browser are you using?
3. Are there any logs on the browser console?

**Comment by town3r** [comment] 2024-01-23 16:11
Ahh good call.

Those Invalid date values seem to only show up on Safari.

iOS iPadOS macOS 

I don't have safari installed on my windows machine.

**Comment by town3r** [comment] 2024-01-23 16:16
Seeing one warning error message in the Dev Console:

```
[Warning] Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info. (moment.min.js, line 1)

Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2024-01-22 12:24:56 CST, _f: undefined, _strict: undefined, _locale: [object Object]
@http://192.168.1.10/admin/scripts/vendor/moment.min.js:1:3266
Nt@http://192.168.1.10/admin/scripts/vendor/moment.min.js:1:21610
Pt@http://192.168.1.10/admin/scripts/vendor/moment.min.js:1:22166
render@http://192.168.1.10/admin/scripts/pi-hole/js/speedresults.js:51:45
@http://192.168.1.10/admin/scripts/vendor/datatables.min.js:43:471
@http://192.168.1.10/admin/scripts/vendor/datatables.min.js:37:234
F@http://192.168.1.10/admin/scripts/vendor/datatables.min.js:42:186
Ka@http://192.168.1.10/admin/scripts/vendor/datatables.min.js:50:96
R@http://192.168.1.10/admin/scripts/vendor/datatables.min.js:41:450
@http://192.168.1.10/admin/scripts/vendor/datatables.min.js:74:398
k@http://192.168.1.10/admin/scripts/vendor/datatables.min.js:60:486
success@http://192.168.1.10/admin/scripts/vendor/datatables.min.js:61:195
c@http://192.168.1.10/admin/scripts/vendor/jquery.min.js:2:28332
fireWith@http://192.168.1.10/admin/scripts/vendor/jquery.min.js:2:29073
l@http://192.168.1.10/admin/scripts/vendor/jquery.min.js:2:80056
@http://192.168.1.10/admin/scripts/vendor/jquery.min.js:2:82500
```

**Comment by ipitio** [comment] 2024-01-23 20:11
Thanks for getting the new update! The invalid date in the log is fixed in the new PR.

I'll need your help to figure out why the speedtests aren't running even though calling speedtest.sh directly works. Could you run `pihole -a -sn` and about a minute or two later `cat /tmp/speedtest.log` —— if a speedtest ran, this file will have its results (otherwise it'll either be empty or have the results from the previous test).

**Comment by town3r** [comment] 2024-01-25 13:44
Sorry for the delay @ipitio & thank you for helping figure this out. :)

Updated via your repo.

Which seems to have resolved the date issue.

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/9438b8bc-fa38-4185-824e-1b83cabf4951)

Two tests ran:
![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/ba4c3559-b012-4378-86a1-2d9f28ddc04b)

But then the pihole-Speedtest.timer command seems to freeze and fail to run correctly?

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/191af8db-134c-46f8-bd95-fba3746b3186)

**Comment by town3r** [comment] 2024-01-25 13:47
Here's the output for 
'systemctl status pihole-speedtest'

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/2c373cef-50ea-4a05-8bee-b46e01137cdc)

**Comment by town3r** [comment] 2024-01-25 13:50
Doesn't look like either of those commands added Speedtest results to the `Speedtest Log`

**Comment by ipitio** [comment] 2024-01-25 15:12
Oh yeah, to get out of the (END) thing you have to press `ctrl+c`.

So the run test now button works now?

Those commands are just to check whether the schedule is active, the speedtest script itself adds results to the log. Are these running?

**Comment by town3r** [comment] 2024-01-25 15:32
Huzzah

Looks like it's working again. :) 

Both the `Start a test now` option and the hourly tests. 🥳

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/4c098b02-d2e9-4193-9f6d-d848f0f78c08)

**Comment by ipitio** [comment] 2024-01-27 10:41
@town3r could you update from my repo again (using the pipe-to-bash, not the button in settings) and let me know if everything still works for you. I've made a few more changes..

**Comment by town3r** [comment] 2024-01-27 16:25
Looks like it's still working!

Including the run test now button.

Did you move the graph below total queries & client activity or had it always been at the bottom.

It was in the middle previously right? lol

Anything else I should look out for?

**Comment by town3r** [comment] 2024-01-27 16:31
Does this link work for anyone?

https://c.speedtest.net/speedtest-servers-static.php

**Comment by ipitio** [comment] 2024-01-27 23:26
Yeah I reorganized/revamped settings, allowing any number of hours or days to be input, moved the chart down, and made a bunch of little fixes.

What do you think of having the chart under the other two? I moved it because it seemed, to me, to interrupt the stacked bar charts, considering it's either not stacked or not a bar chart. Did you like it better between?

That link returns XML so doesn't work in iOS Safari. I'm not sure what the new Safaris can do, but maybe you can download the page (which should download the XML). I could probably do something about this..

**Comment by town3r** [comment] 2024-01-28 17:45
> What do you think of having the chart under the other two? I moved it because it seemed, to me, to interrupt the stacked bar charts, considering it's either not stacked or not a bar chart. Did you like it better between?

I like it! I had just gotten used to it being in the middle. 

> That link returns XML so doesn't work in iOS Safari. I'm not sure what the new Safaris can do, but maybe you can download the page (which should download the XML). I could probably do something about this..

Good catch, had to use a safari extension for it to show up as not blank.

**Comment by ipitio** [comment] 2024-01-30 08:13
If you wanna review the latest changes before they get merged, now would be a good time to update using my repo again :)

**Comment by town3r** [comment] 2024-01-30 13:54
Updated!
Searching for any changes :D

**Comment by town3r** [comment] 2024-01-30 14:21
Oh nice!
That show closest server box is 🔥

**Comment by town3r** [comment] 2024-01-30 16:09
Hmm the results in the Server list seem to be kinda random or off compaired to running `speedtest -L`.

Oh duh, it's just pulling w/e is outputted on `https://c.speedtest.net/speedtest-servers-static.php`

Which for me only lists one server in my city, where `speedtest -L` lists 5 in my city and a good number of additional options close by.

Not to go totally off the rails, do you think you could make it so hitting `Show closes servers` triggers `speedtest -L` being ran instead of pulling from `speedtest-servers-static.php`?

**Comment by arevindh** [comment] 2024-01-30 16:48
> Hmm the results in the Server list seem to be kinda random or off compaired to running `speedtest -L`.
> 
> Oh duh, it's just pulling w/e is outputted on `https://c.speedtest.net/speedtest-servers-static.php`
> 
> Which for me only lists one server in my city, where `speedtest -L` lists 5 in my city and a good number of additional options close by.
> 
> Not to go totally off the rails, do you think you could make it so hitting `Show closes servers` triggers `speedtest -L` being ran instead of pulling from `speedtest-servers-static.php`?

Can you try  https://www.speedtest.net/api/js/servers?engine=js&limit=10&https_functional=true

**Comment by town3r** [comment] 2024-01-30 16:54
Those look much better

**Comment by ipitio** [comment] 2024-01-30 18:06
Alright, I updated it to use that link, you should have all your servers now. I'd use `speedtest -L` but it seems to have a bug when called from a php environment that causes it to fail.

**Comment by town3r** [comment] 2024-01-30 18:07
Amazing!
Looks much better now. :)

**Comment by arevindh** [comment] 2024-01-31 16:46
> Amazing!
> Looks much better now. :)

Changes merged, can you. Check if everything is fine?

**Comment by town3r** [comment] 2024-01-31 20:53
And now these after attempting @ipitio update script and then yours @arevindh 

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/b3b83b9c-d62f-4589-bbfc-5287987b87a6)

**Comment by ipitio** [comment] 2024-01-31 20:56
I have a fix submitted for that. Right now you can run the script with "un" to uninstall, then without args or with "up" to install

**Comment by town3r** [comment] 2024-02-01 13:37
![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/0a7b7382-5c22-41e8-9784-9455555c8a61)

**Comment by town3r** [comment] 2024-02-01 13:38
![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/6d02ab3c-5a10-4341-bbf8-bc56ac5bd858)

**Comment by town3r** [comment] 2024-02-09 15:16
Tried to uninstall and reinstall but it fails.

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/26f5a06e-8a8a-46d5-a9a2-bfa6fc997a25)

**Comment by town3r** [comment] 2024-02-09 15:37
I went through the [manual uninstall](https://github.com/arevindh/pihole-speedtest/wiki/Uninstalling-Speedtest-Mod) steps and found the Web Interface still shows as `VDEV (Head, V5.21.3)`

**Comment by arevindh** [comment] 2024-02-09 17:06
I think there is some issue  with curl command

try this `sudo apt install gnutls-bin`

**Comment by town3r** [comment] 2024-02-09 17:23
![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/46bfaf40-c620-4b96-b7e1-b4bf68a9b2da)

**Comment by ipitio** [comment] 2024-02-09 17:34
That seems to be related to the fatal error, I think, which the new PRs fix

**Comment by town3r** [comment] 2024-02-13 14:41
Nice!
Any idea when the fixes will be pushed out? 😄

**Comment by ipitio** [comment] 2024-02-13 16:22
I guess now haha

**Comment by town3r** [comment] 2024-02-14 14:52
I think it worked.
Other than the error from Pihole directly.

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/f6a0c0c3-2c6a-42d4-997b-5734f44ee7c2)

**Comment by ipitio** [comment] 2024-02-14 15:39
Huh I guess I didn't fix it, but now I have a better idea of why that happens. To test my hypothesis, could you update using my dev repo? If I'm right, you won't encounter the issue because it doesn't pin admin to a tag for dev purposes.

**Comment by ipitio** [comment] 2024-02-17 13:49
I think #159 should fix it.

**Comment by town3r** [comment] 2024-02-21 14:11
Two issues currently.

1. Unable to update the Testing interval value to anything but 0 resulting in no tests running.

2. Unable to update.

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/8aa94dc8-4f8b-4ed9-b178-d29eb3095944)

**Comment by town3r** [comment] 2024-02-21 14:12
I'll try uninstalling and reinstalling the mod fresh.

**Comment by town3r** [comment] 2024-02-21 18:06
Yup!

When the Mod was installed, anything other than 0 entered in that field after saving and the auto refresh of the page, it would be back to 0.

Didn't see anything pop-up in the recent logs when clicking the button.

**Comment by ipitio** [comment] 2024-02-21 21:28
Could you try installing the mod from my repo? I have verbose logging enabled there so I can see where exactly that error happens.

    curl -sSLN https://github.com/ipitio/pihole-speedtest/raw/ipitio/mod.sh | sudo bash

I also can't reproduce the testing interval issue; what does the "show status" say after you try changing the interval?

**Comment by town3r** [comment] 2024-02-21 21:35
Fresh install via your repo seems to work successfully.

The testing interval issue also seems to be gone as well.
Schedule is inactive is what it used to say.

Where now it's active w/ a count don to next run.

**Comment by ipitio** [comment] 2024-02-21 21:43
That's interesting. Well, since it's working for you now let's wait till sid merges my latest PRs and see if it still doesn't work for you then.

**Comment by town3r** [comment] 2024-02-21 21:50
Once merged, should I uninstalled, and then reinstall fresh from his repo?

Could switching between the two repos when running the upgrade command be breaking things?

**Comment by ipitio** [comment] 2024-02-21 21:55
You should be able to just upgrade with the script in sid's repo. Upgrading, uninstalling, even switching repos should be transparent.

**Comment by town3r** [comment] 2024-02-22 12:28
Got this after seeing the update was pushed early this morning.

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/c5bd2f14-1955-491e-93cb-f4610be5d92e)

**Comment by town3r** [comment] 2024-02-28 01:37
Looks like it worked!
No error as far as i can tell.

**Closed** 2024-02-28 02:08 UTC
Labels: bug

**Comment by town3r** [comment] 2024-02-28 02:11
![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/8470efbc-5b16-4dec-ac56-bce9082f9d47)

**Comment by ipitio** [comment] 2024-02-28 02:13
Try again, I pushed the wrong tag

**Comment by ipitio** [comment] 2024-02-28 02:14
Also, it's `-s up` if you want to run the update!

**Comment by town3r** [comment] 2024-02-28 02:19
Ahh there we go!
![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/e0b5c3a6-568f-458b-b67d-1d551e204f61)
